### ISSUE TITLE
Parsed member do not have a connection_status key

### ISSUE THREAD

**Issue by MrLepage** [sendbird/sendbird-sdk-flutter#7]
`Member`, `Sender` and `User` model parsing are looking for a `connection_status` key which does not exist in the json parsed. 
It results in a `UserConnectionStatus.notAvailable` returned when we want to display the connection status of a user.

Does this status mean that the info of the **connection status** is not available or that the **user** is not available?
I do not see mention of this UserConnectionStatus in the documentation which leads to confusion.

I see a `is_online` key which is not parsed? Is it an API update that has not been handled by the SDK yet?

![Capture d’écran 2021-06-23 à 10 03 37](https://user-images.githubusercontent.com/18703480/123060388-faf42d80-d40a-11eb-95d1-f4a3480c3870.png)

I also see in the documentation that it is advised to periodically make an `ApplicationUserListQuery` specifying `userIds` to keep track of the connection status of users.

Do you advise to make this query each time new channels are added or fetched and keep/save the user list returned to query their connection status when needed? (ex : in a message cell avatar or in a channel member cell avatar)

I think this part of the documentation needs more guidance :)

**Comment by intoxicated** [comment]
@MrLepage Thanks for the report. It is definitely mismatched, I will fix this issue on next patch.

For the usage of `ApplicationUserListQuery`, it all depends on how you want to display online status on UI (we do not support liveness for online status at the moment, this is mostly due to scalability issue). You can periodically call the query (I do not recommend to call this too frequently like every second) with some reasonable interval.

**Comment by intoxicated** [comment]
Fixed in `3.1.0-nullsafety`
